/* =====================================================
   WÖRTERLISTE
   Die Schwierigkeit ergibt sich automatisch aus der
   Wortlänge (siehe JS/eulenschule.js):
   bis 5 Buchstaben = leicht, 6-8 = mittel, ab 9 = schwer
   ===================================================== */

const words = [

    /* ---------- TIERE ---------- */
    { category: "Tiere", word: "KATZE" },
    { category: "Tiere", word: "FUCHS" },
    { category: "Tiere", word: "PANDA" },
    { category: "Tiere", word: "OTTER" },
    { category: "Tiere", word: "EULE" },
    { category: "Tiere", word: "ESEL" },
    { category: "Tiere", word: "WOLF" },
    { category: "Tiere", word: "KAMEL" },
    { category: "Tiere", word: "HUND" },
    { category: "Tiere", word: "MAUS" },
    { category: "Tiere", word: "PFERD" },
    { category: "Tiere", word: "SCHAF" },
    { category: "Tiere", word: "ZIEGE" },
    { category: "Tiere", word: "AFFE" },
    { category: "Tiere", word: "TIGER" },
    { category: "Tiere", word: "IGEL" },
    { category: "Tiere", word: "REH" },
    { category: "Tiere", word: "ADLER" },
    { category: "Tiere", word: "BIENE" },
    { category: "Tiere", word: "KUH" },
    { category: "Tiere", word: "ZEBRA" },
    { category: "Tiere", word: "ROBBE" },
    { category: "Tiere", word: "LUCHS" },
    { category: "Tiere", word: "KOALA" },
    { category: "Tiere", word: "SCHLANGE" },
    { category: "Tiere", word: "HAMSTER" },
    { category: "Tiere", word: "DELFIN" },
    { category: "Tiere", word: "GIRAFFE" },
    { category: "Tiere", word: "ELEFANT" },
    { category: "Tiere", word: "KROKODIL" },
    { category: "Tiere", word: "PINGUIN" },
    { category: "Tiere", word: "WALFISCH" },
    { category: "Tiere", word: "HAIFISCH" },
    { category: "Tiere", word: "SPINNE" },
    { category: "Tiere", word: "HIRSCH" },
    { category: "Tiere", word: "STORCH" },
    { category: "Tiere", word: "FROSCH" },
    { category: "Tiere", word: "SCHNECKE" },
    { category: "Tiere", word: "AMEISE" },
    { category: "Tiere", word: "FLAMINGO" },
    { category: "Tiere", word: "GORILLA" },
    { category: "Tiere", word: "NASHORN" },
    { category: "Tiere", word: "MAULWURF" },
    { category: "Tiere", word: "SCHMETTERLING" },
    { category: "Tiere", word: "FLUSSPFERD" },
    { category: "Tiere", word: "STACHELSCHWEIN" },
    { category: "Tiere", word: "MEERSCHWEINCHEN" },
    { category: "Tiere", word: "SCHIMPANSE" },
    { category: "Tiere", word: "FLEDERMAUS" },
    { category: "Tiere", word: "MURMELTIER" },
    { category: "Tiere", word: "KLAPPERSCHLANGE" },

    /* ---------- OBST ---------- */
    { category: "Obst", word: "APFEL" },
    { category: "Obst", word: "BANANE" },
    { category: "Obst", word: "BIRNE" },
    { category: "Obst", word: "KIWI" },
    { category: "Obst", word: "BEERE" },
    { category: "Obst", word: "MANGO" },
    { category: "Obst", word: "ERDBEERE" },
    { category: "Obst", word: "KIRSCHEN" },
    { category: "Obst", word: "ANANAS" },
    { category: "Obst", word: "TRAUBEN" },
    { category: "Obst", word: "ZITRONE" },
    { category: "Obst", word: "PFLAUME" },
    { category: "Obst", word: "MELONE" },
    { category: "Obst", word: "PFIRSICH" },
    { category: "Obst", word: "AVOCADO" },
    { category: "Obst", word: "HIMBEERE" },
    { category: "Obst", word: "KOKOSNUSS" },
    { category: "Obst", word: "WASSERMELONE" },
    { category: "Obst", word: "BROMBEERE" },
    { category: "Obst", word: "HEIDELBEERE" },
    { category: "Obst", word: "GRAPEFRUIT" },

    /* ---------- BAUSTELLE ---------- */
    { category: "Baustelle", word: "KRAN" },
    { category: "Baustelle", word: "SAND" },
    { category: "Baustelle", word: "NAGEL" },
    { category: "Baustelle", word: "BAGGER" },
    { category: "Baustelle", word: "ZEMENT" },
    { category: "Baustelle", word: "BETON" },
    { category: "Baustelle", word: "STEIN" },
    { category: "Baustelle", word: "MAUER" },
    { category: "Baustelle", word: "HAMMER" },
    { category: "Baustelle", word: "LEITER" },
    { category: "Baustelle", word: "ZIEGEL" },
    { category: "Baustelle", word: "SCHUTT" },
    { category: "Baustelle", word: "BAUHELM" },
    { category: "Baustelle", word: "SCHRAUBE" },
    { category: "Baustelle", word: "BAUSTELLE" },
    { category: "Baustelle", word: "BOHRMASCHINE" },
    { category: "Baustelle", word: "BAUARBEITER" },
    { category: "Baustelle", word: "SCHUBKARRE" },
    { category: "Baustelle", word: "WERKZEUGKASTEN" },

    /* ---------- BERUFE ---------- */
    { category: "Berufe", word: "ARZT" },
    { category: "Berufe", word: "KOCH" },
    { category: "Berufe", word: "MALER" },
    { category: "Berufe", word: "BAUER" },
    { category: "Berufe", word: "PILOT" },
    { category: "Berufe", word: "LEHRER" },
    { category: "Berufe", word: "KELLNER" },
    { category: "Berufe", word: "RICHTER" },
    { category: "Berufe", word: "FRISEUR" },
    { category: "Berufe", word: "POLIZIST" },
    { category: "Berufe", word: "ZAHNARZT" },
    { category: "Berufe", word: "TIERARZT" },
    { category: "Berufe", word: "INGENIEUR" },
    { category: "Berufe", word: "SCHREINER" },
    { category: "Berufe", word: "SCHNEIDER" },
    { category: "Berufe", word: "APOTHEKER" },
    { category: "Berufe", word: "ELEKTRIKER" },
    { category: "Berufe", word: "MECHANIKER" },
    { category: "Berufe", word: "JOURNALIST" },
    { category: "Berufe", word: "FEUERWEHRMANN" },
    { category: "Berufe", word: "SCHAUSPIELER" },
    { category: "Berufe", word: "KRANKENSCHWESTER" },

    /* ---------- FILMFIGUREN ---------- */
    { category: "Filmfiguren", word: "ELSA" },
    { category: "Filmfiguren", word: "NEMO" },
    { category: "Filmfiguren", word: "OLAF" },
    { category: "Filmfiguren", word: "MAUI" },
    { category: "Filmfiguren", word: "BUZZ" },
    { category: "Filmfiguren", word: "REX" },
    { category: "Filmfiguren", word: "GOOFY" },
    { category: "Filmfiguren", word: "PLUTO" },
    { category: "Filmfiguren", word: "MULAN" },
    { category: "Filmfiguren", word: "BAMBI" },
    { category: "Filmfiguren", word: "DORY" },
    { category: "Filmfiguren", word: "SIMBA" },
    { category: "Filmfiguren", word: "MICKEY" },
    { category: "Filmfiguren", word: "DUMBO" },
    { category: "Filmfiguren", word: "ARIEL" },
    { category: "Filmfiguren", word: "WOODY" },
    { category: "Filmfiguren", word: "BATMAN" },
    { category: "Filmfiguren", word: "SHREK" },
    { category: "Filmfiguren", word: "MOANA" },
    { category: "Filmfiguren", word: "STITCH" },
    { category: "Filmfiguren", word: "DONALD" },
    { category: "Filmfiguren", word: "TIGGER" },
    { category: "Filmfiguren", word: "AURORA" },
    { category: "Filmfiguren", word: "MERIDA" },
    { category: "Filmfiguren", word: "TARZAN" },
    { category: "Filmfiguren", word: "ALADDIN" },
    { category: "Filmfiguren", word: "HERKULES" },
    { category: "Filmfiguren", word: "PETERPAN" },
    { category: "Filmfiguren", word: "SPIDERMAN" },
    { category: "Filmfiguren", word: "RAPUNZEL" },
    { category: "Filmfiguren", word: "PINOCCHIO" },
    { category: "Filmfiguren", word: "ASCHENPUTTEL" },
    { category: "Filmfiguren", word: "SCHNEEWITTCHEN" },

    /* ---------- ORTE ---------- */
    { category: "Orte", word: "SEE" },
    { category: "Orte", word: "ZOO" },
    { category: "Orte", word: "PARK" },
    { category: "Orte", word: "WALD" },
    { category: "Orte", word: "BURG" },
    { category: "Orte", word: "TURM" },
    { category: "Orte", word: "MARKT" },
    { category: "Orte", word: "FLUSS" },
    { category: "Orte", word: "INSEL" },
    { category: "Orte", word: "HAFEN" },
    { category: "Orte", word: "BERGE" },
    { category: "Orte", word: "STADT" },
    { category: "Orte", word: "STRAND" },
    { category: "Orte", word: "SCHULE" },
    { category: "Orte", word: "MUSEUM" },
    { category: "Orte", word: "GARTEN" },
    { category: "Orte", word: "KIRCHE" },
    { category: "Orte", word: "THEATER" },
    { category: "Orte", word: "BAHNHOF" },
    { category: "Orte", word: "FLUGHAFEN" },
    { category: "Orte", word: "SPIELPLATZ" },
    { category: "Orte", word: "SUPERMARKT" },
    { category: "Orte", word: "BIBLIOTHEK" },
    { category: "Orte", word: "KRANKENHAUS" },

    /* ---------- ESSEN ---------- */
    { category: "Essen", word: "EIS" },
    { category: "Essen", word: "REIS" },
    { category: "Essen", word: "BROT" },
    { category: "Essen", word: "KEKS" },
    { category: "Essen", word: "HONIG" },
    { category: "Essen", word: "PIZZA" },
    { category: "Essen", word: "SALAT" },
    { category: "Essen", word: "SUPPE" },
    { category: "Essen", word: "WURST" },
    { category: "Essen", word: "NUDELN" },
    { category: "Essen", word: "KUCHEN" },
    { category: "Essen", word: "BURGER" },
    { category: "Essen", word: "WAFFEL" },
    { category: "Essen", word: "JOGHURT" },
    { category: "Essen", word: "PUDDING" },
    { category: "Essen", word: "OMELETT" },
    { category: "Essen", word: "EISCREME" },
    { category: "Essen", word: "SANDWICH" },
    { category: "Essen", word: "SCHNITZEL" },
    { category: "Essen", word: "SPAGHETTI" },
    { category: "Essen", word: "MARMELADE" },
    { category: "Essen", word: "SCHOKOLADE" },
    { category: "Essen", word: "KARTOFFELN" },
    { category: "Essen", word: "PFANNKUCHEN" },

    /* ---------- NATUR ---------- */
    { category: "Natur", word: "BLITZ" },
    { category: "Natur", word: "FROST" },
    { category: "Natur", word: "NEBEL" },
    { category: "Natur", word: "STURM" },
    { category: "Natur", word: "EBBE" },
    { category: "Natur", word: "FLUT" },
    { category: "Natur", word: "SUMPF" },
    { category: "Natur", word: "TEICH" },
    { category: "Natur", word: "REGEN" },
    { category: "Natur", word: "SONNE" },
    { category: "Natur", word: "WOLKE" },
    { category: "Natur", word: "VULKAN" },
    { category: "Natur", word: "SCHNEE" },
    { category: "Natur", word: "ERDBEBEN" },
    { category: "Natur", word: "GEWITTER" },
    { category: "Natur", word: "GLETSCHER" },
    { category: "Natur", word: "DSCHUNGEL" },
    { category: "Natur", word: "REGENBOGEN" },
    { category: "Natur", word: "WASSERFALL" },
    { category: "Natur", word: "WIRBELSTURM" },
    { category: "Natur", word: "SONNENSCHEIN" },

    /* ---------- FAHRZEUGE ---------- */
    { category: "Fahrzeuge", word: "BUS" },
    { category: "Fahrzeuge", word: "ZUG" },
    { category: "Fahrzeuge", word: "AUTO" },
    { category: "Fahrzeuge", word: "BOOT" },
    { category: "Fahrzeuge", word: "TAXI" },
    { category: "Fahrzeuge", word: "TRAM" },
    { category: "Fahrzeuge", word: "KANU" },
    { category: "Fahrzeuge", word: "SCHIFF" },
    { category: "Fahrzeuge", word: "ROLLER" },
    { category: "Fahrzeuge", word: "RAKETE" },
    { category: "Fahrzeuge", word: "FAHRRAD" },
    { category: "Fahrzeuge", word: "TRAKTOR" },
    { category: "Fahrzeuge", word: "FLUGZEUG" },
    { category: "Fahrzeuge", word: "MOTORRAD" },
    { category: "Fahrzeuge", word: "LASTWAGEN" },
    { category: "Fahrzeuge", word: "SEGELBOOT" },
    { category: "Fahrzeuge", word: "HUBSCHRAUBER" },
    { category: "Fahrzeuge", word: "POLIZEIAUTO" },
    { category: "Fahrzeuge", word: "KRANKENWAGEN" },
    { category: "Fahrzeuge", word: "FEUERWEHRAUTO" },

];
